// Generated by CoffeeScript 1.8.0
define(function(require, exports, module) {
  'use strict';
  var AppInit, FileSystem, utfCore, utfUI;
  AppInit = brackets.getModule("utils/AppInit");
  FileSystem = brackets.getModule("filesystem/FileSystem");
  utfCore = require('src/core');
  utfUI = require('src/ui');
  AppInit.appReady(function() {
    utfUI.init();
    utfCore.init();
    return utfUi.initStyleSheet('styles/main.css');
  });
  return exports.handleDetectEncoding = utfCore.handleDetectEncoding;
});
