// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var chardet, cmdConvertFileEncoding, cmdGetFilesEncoding, fs, iconv, init, jschardet;
  fs = require('fs');
  iconv = require('iconv-lite');
  chardet = require('node-chardet');
  jschardet = require('jschardet');
  cmdGetFilesEncoding = function(dirPath, dig) {
    var diggedFile, file, filePath, filename, listFiles, lsDiggedFiles, lsFiles, _i, _j, _len, _len1, _ref;
    if (dig == null) {
      dig = false;
    }
    lsFiles = fs.readdirSync(dirPath);
    listFiles = [];
    for (_i = 0, _len = lsFiles.length; _i < _len; _i++) {
      filename = lsFiles[_i];
      if ((filename != null) && filename !== '.DS_Store' && filename !== /~$/) {
        filePath = dirPath + filename;
        if (!fs.lstatSync(filePath).isDirectory()) {
          file = jschardet.detect(fs.readFileSync(filePath));
          file.name = filename;
          file.path = filePath;
          file.confidence *= 100;
          listFiles.push(file);
        } else if (dig) {
          if (filePath !== /\/$/) {
            filePath += '/';
          }
          lsDiggedFiles = cmdGetFilesEncoding(filePath, dig);
          _ref = lsDiggedFiles.files;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            diggedFile = _ref[_j];
            listFiles.push(diggedFile);
          }
        }
      }
    }
    return {
      files: listFiles
    };
  };
  cmdConvertFileEncoding = function(filePath) {
    var file, fileDir, fileExt, fileName, newFile, str, str_enc;
    file = fs.readFileSync(filePath);
    str = iconv.decode(file, jschardet.detect(file).encoding);
    str_enc = iconv.encode(str, 'utf8');
    fileDir = filePath.substring(0, filePath.lastIndexOf('/') + 1);
    fileName = filePath.substring(filePath.lastIndexOf('/') + 1, filePath.lastIndexOf('.'));
    fileExt = filePath.substring(filePath.lastIndexOf('.'));
    newFile = fileDir + fileName + '.utf8' + fileExt;
    fs.writeFileSync(newFile, str_enc);
    return newFile;
  };
  init = function(DomainManager) {
    var domainName;
    domainName = 'bracketsUtfConverter';
    if (!DomainManager.hasDomain(domainName)) {
      DomainManager.registerDomain(domainName, {
        major: 0,
        minor: 1
      });
    }
    DomainManager.registerCommand(domainName, 'getFilesEncoding', cmdGetFilesEncoding, false, 'Return a test value', [
      {
        name: 'path',
        type: 'string',
        description: 'File path'
      }
    ]);
    DomainManager.registerCommand(domainName, 'convertFileEncoding', cmdConvertFileEncoding, false, 'Create a UTF8 formated file', []);
  };
  exports.init = init;
})();
