// Generated by CoffeeScript 1.8.0
define(function(require, exports, module) {
  "use strict";
  var PREFERENCES_KEY, PreferencesManager, defaultPreferences, utf_prefs, _;
  PREFERENCES_KEY = "utf8-converter";
  _ = brackets.getModule("thirdparty/lodash");
  PreferencesManager = brackets.getModule("preferences/PreferencesManager");
  utf_prefs = PreferencesManager.getExtensionPrefs(PREFERENCES_KEY);
  defaultPreferences = {
    "allowDigging": {
      "type": "boolean",
      "value": true
    },
    "allowAutoConvert": {
      "type": "boolean",
      "value": false
    }
  };
  _.each(defaultPreferences, function(definition, key) {
    if (definition.os && definition.os[brackets.platform]) {
      utf_prefs.definePreference(key, definition.type, definition.os[brackets.platform].value);
    } else {
      utf_prefs.definePreference(key, definition.type, definition.value);
    }
  });
  utf_prefs.save();
  utf_prefs.getAll = function() {
    var obj;
    obj = {};
    _.each(defaultPreferences((function(_this) {
      return function(defintion, key) {
        return obj[key] = _this.get(key);
      };
    })(this)));
    return obj;
  };
  utf_prefs.getDefaults = function() {
    var obj;
    obj = {};
    _.each(defaultPreferences, (function(_this) {
      return function(definition, key) {
        var defaultValue;
        return defaultValue = definition.os[brackets.platform].value(definition.os && definition.os[brackets.platform] ? void 0 : defaultValue = definition.value);
      };
    })(this));
    return obj;
  };
  utf_prefs.persist = (function(_this) {
    return function(key, value) {
      _this.set(key, value);
      return _this.save();
    };
  })(this);
  return module.exports = utf_prefs;
});
